


var exp1={
    "data": [
        {
            "id": "00000111-e27b-45ca-a8e6-75f989a6697a",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-30T15:15:19.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "3926720",
            "br_number_with_check_digit": "39267201",
            "company_english_name": "YAT PIN TONG INTERNATIONAL LIMITED",
            "company_chinese_name": "一品堂國際有限公司",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": 1578021,
            "matched_at": "2022-05-31T07:55:48",
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "0000022c-fa34-4d73-b934-bcd89f0e2a13",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-03T02:21:06.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "2197456",
            "br_number_with_check_digit": "21974563",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The input BR Number cannot be found in the Business Register.&nbsp; [556-E-1008]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00000251-5e29-4bd0-9d99-851aa5e11563",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-04-24T17:22:03.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "2941729",
            "br_number_with_check_digit": "29417294",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The Input BR Number cannot be found in the Business Register&nbsp; [556-E-1035]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "000003ef-d083-494e-8112-e4e9125c3c6a",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-04-21T18:37:47.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "0724053",
            "br_number_with_check_digit": "07240532",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The input BR Number cannot be found in the Business Register.&nbsp; [556-E-1008]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00000833-0acd-4f8b-8ce4-be4ecb48fd3d",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-25T08:53:07.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "6645293",
            "br_number_with_check_digit": "66452936",
            "company_english_name": "HONGKONG KINGTAI INDUSTRY CO., LIMITED",
            "company_chinese_name": "香港金泰實業有限公司",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": 660039,
            "matched_at": "2022-05-31T04:55:48",
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00000925-74a8-4f65-bfa9-13ea6d08eed1",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-29T23:47:52.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "4139718",
            "br_number_with_check_digit": "41397189",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The Input BR Number cannot be found in the Business Register&nbsp; [556-E-1035]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00000c42-6913-46c5-aee6-68ae672a5bfe",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-17T00:14:29.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "5039143",
            "br_number_with_check_digit": "50391431",
            "company_english_name": "PROTECH ENVIRONMENT CARE INSULATING      ENGINEERING CO",
            "company_chinese_name": "保泰環保隔熱工程公司",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00001743-f1bc-44a1-abfa-6b1746ef81b6",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-04-26T14:35:35.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "2264788",
            "br_number_with_check_digit": "22647884",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The Input BR Number cannot be found in the Business Register&nbsp; [556-E-1035]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00001924-96ba-4960-a36a-8583450a11fc",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-03T08:50:04.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "4807204",
            "br_number_with_check_digit": "48072045",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The Input BR Number cannot be found in the Business Register&nbsp; [556-E-1035]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00001aaf-cdba-4ecc-991e-9ab9d61b8556",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-19T14:16:50.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "5924553",
            "br_number_with_check_digit": "59245534",
            "company_english_name": "THE HUNT APPAREL LIMITED",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00001ed3-81df-411d-aba9-23fc2bf5f8f5",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-18T23:26:29.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "5783220",
            "br_number_with_check_digit": "57832208",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The Input BR Number cannot be found in the Business Register&nbsp; [556-E-1035]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00001ed7-eeec-4a1a-867f-a36521f17ed6",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-20T23:44:02.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "5967340",
            "br_number_with_check_digit": "59673408",
            "company_english_name": "DEGUOSENTAOWEIYU CO., LIMITED",
            "company_chinese_name": "德國森陶衛浴有限公司",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": 1929829,
            "matched_at": "2022-05-31T07:55:48",
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00001f4c-9c0d-4960-a081-bc7e979f38c9",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-23T07:48:34.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "2068767",
            "br_number_with_check_digit": "20687672",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The input BR Number cannot be found in the Business Register.&nbsp; [556-E-1008]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "0000211b-c3f6-496b-82c7-432f8cd02418",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-02T13:30:16.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "5140102",
            "br_number_with_check_digit": "51401021",
            "company_english_name": "CLOUDTERRAIN LIMITED",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "0000234e-55f8-47b4-a2f1-5a87625eeb45",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-04-26T10:53:45.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "3110887",
            "br_number_with_check_digit": "31108877",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The input BR Number cannot be found in the Business Register.&nbsp; [556-E-1008]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "000024bb-e07d-4d37-a89e-3f671d4d3ed9",
            "status": "Invalid",
            "user_created": "0f0b0c7f-d98c-4f9c-8ba2-7f9b15dff36a",
            "date_created": "2022-04-21T15:00:30.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "0301229",
            "br_number_with_check_digit": "03012294",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The input BR Number cannot be found in the Business Register.&nbsp; [556-E-1008]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "000025db-c2ba-4f09-abb3-4730f281ceb0",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-04-26T16:27:10.000Z",
            "user_updated": "29dd5c12-beff-4703-bc25-45830e880822",
            "date_updated": "2022-05-02T04:33:00.000Z",
            "br_number_without_check_digit": "4120823",
            "br_number_with_check_digit": "41208233",
            "company_english_name": "CSGO_SKINS_SNIPER",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "0000261a-b1fb-41c2-a483-5ff42a997b26",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-26T01:36:03.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "6277457",
            "br_number_with_check_digit": "62774570",
            "company_english_name": "STOCKHERO LIMITED",
            "company_chinese_name": "淘金者（香港）控股有限公司",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": 2430518,
            "matched_at": "2022-05-31T04:55:48",
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "0000263f-eb82-4314-802d-d63f29469342",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-16T00:42:02.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "5016124",
            "br_number_with_check_digit": "50161242",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The input BR Number cannot be found in the Business Register.&nbsp; [556-E-1008]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "0000267c-1307-4565-90a3-ced55fd9b23b",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-14T08:42:34.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "5483302",
            "br_number_with_check_digit": "54833023",
            "company_english_name": "LOVE HEART NAIL",
            "company_chinese_name": "愛心美甲",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00002860-4fb3-40ba-b87e-503f006a677f",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-24T10:35:19.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "6663383",
            "br_number_with_check_digit": "66633833",
            "company_english_name": "KENDLE LIMITED",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": 2708560,
            "matched_at": "2022-05-31T07:30:03",
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00002bed-2ceb-45f2-b1c5-e54f496b6d3f",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-06-02T11:11:10.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "3517128",
            "br_number_with_check_digit": "35171286",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The input BR Number cannot be found in the Business Register.&nbsp; [556-E-1008]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00002c82-0b4f-4882-b823-71e062580670",
            "status": "Invalid",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-28T18:03:27.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "4314969",
            "br_number_with_check_digit": "43149697",
            "company_english_name": "",
            "company_chinese_name": "",
            "company_address": null,
            "error_message": "The Input BR Number cannot be found in the Business Register&nbsp; [556-E-1035]",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00002df0-07eb-4f7c-a489-98cb559d0a62",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-21T14:59:30.000Z",
            "user_updated": null,
            "date_updated": null,
            "br_number_without_check_digit": "5898003",
            "br_number_with_check_digit": "58980034",
            "company_english_name": "SHANGHAI IHOME CO., LIMITED",
            "company_chinese_name": "上海歐皇有限公司",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": 1635388,
            "matched_at": "2022-05-31T07:55:48",
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
        {
            "id": "00002f9d-89e8-47ec-8f70-6c9b1a920527",
            "status": "Active",
            "user_created": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_created": "2022-05-19T21:56:22.000Z",
            "user_updated": "fc59ca46-8e19-43de-8ab3-dc72528256d8",
            "date_updated": "2022-06-05T04:20:26.000Z",
            "br_number_without_check_digit": "6354188",
            "br_number_with_check_digit": "63541889",
            "company_english_name": "BUY THE WORLD CO., LIMITED",
            "company_chinese_name": "百德沃貿易（香港）有限公司",
            "company_address": null,
            "error_message": "",
            "expiration_date": null,
            "matched_company": null,
            "matched_at": null,
            "natural_of_business": null,
            "certificate_number": null,
            "commencement_date": null,
            "branch_name_english": null,
            "branch_name_chinese": null,
            "fee_and_levy": null,
            "remarks": null,
            "converted_json": null,
            "references": []
        },
    ]
}
var  munber=exp1.data

function getSelectHkBr(hkBr){
    var number1 = [];
    for(k=0;k<hkBr.length;k++){
     var  stringDate= hkBr[k].date_created
     var  date1   =new Date(stringDate)
        number1.push(date1)
    }
    console.log("是否进入")
    for(var i=0;i<number1.length-1;i++){
        for (var j = 0; j < number1.length - 1; j++) {
            if(number1[j]<number1[j+1]==true){
                var temp = number1[j+1]
                 number1[j+1] = number1[j]
                 number1[j] = temp
            }
        }
    }
    for(var t=0;t<hkBr.length;t++){
        if(number1[0].toString() == new Date(hkBr[t].date_created) ){
           console.log("ok")
            return hkBr[t]
        }else {
        }
    }
    return  hkBr[t]
}
var selectHkBr=getSelectHkBr(munber);
console.log(selectHkBr)


